In [1]:
import torch

In [2]:
a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)

In [3]:
a

tensor([5.], requires_grad=True)

In [4]:
b

tensor([6.], requires_grad=True)

In [5]:
type(a)

torch.Tensor

In [6]:
y = a**3 - b ** 2
y

tensor([89.], grad_fn=<SubBackward0>)

In [7]:
#dy/da = 3*a**2 = 75
#dy/db = -2b = -12

In [8]:
print(a.grad)

None


In [9]:
y.backward()

In [11]:
a.grad

tensor([75.])

In [12]:
b.grad

tensor([-12.])

- W and b are parameters, which we need to optimize.thus, we need to be able to compute the gradients of loss function with respect to those variables.
- In order to do that, we set the required_grad = True for those tenosrs.

In [14]:
w = torch.randn(10,1, requires_grad = True)
b = torch.randn(1, requires_grad = True)

In [15]:
w

tensor([[ 1.1248],
        [-0.6565],
        [-0.2815],
        [-1.9687],
        [ 0.8520],
        [ 0.2365],
        [ 0.5617],
        [-0.1154],
        [-0.4625],
        [ 0.0360]], requires_grad=True)

In [16]:
b

tensor([-0.5346], requires_grad=True)

In [17]:
x = torch.rand(1, 10)
x

tensor([[0.8039, 0.1727, 0.9479, 0.4151, 0.7902, 0.1132, 0.0360, 0.7497, 0.9182,
         0.9580]])

In [18]:
output = torch.matmul(x, w) + b #input * weights  + bias
output

tensor([[-0.5842]], grad_fn=<AddBackward0>)

In [19]:
#calculate the loss
loss = 1 - output
loss 

tensor([[1.5842]], grad_fn=<RsubBackward1>)

In [20]:
#Backward propagation 
#Here we need to compute the derivatives of our loss function with respect to parameters, 
#we need dloss/ dw and dloss/ db under some fixed values of x and y.
#To compute those derivatives, we call loss.backward() function.
#then retrieve the values from w.grad and b.grad.
loss.backward() 

In [21]:
w.grad

tensor([[-0.8039],
        [-0.1727],
        [-0.9479],
        [-0.4151],
        [-0.7902],
        [-0.1132],
        [-0.0360],
        [-0.7497],
        [-0.9182],
        [-0.9580]])

In [22]:
b.grad

tensor([-1.])

- By default, all tensors with requires_grad=True are tracking their computational history and support gradient computation.
- We can stop tracking computations by surrounding our computation code with torch.no_grad() block

In [24]:
#Here updating weights 
#learning rate = 0.001 
with torch.no_grad():
    w = w - 0.001 * w.grad.data

In [25]:
w

tensor([[ 1.1256],
        [-0.6563],
        [-0.2806],
        [-1.9683],
        [ 0.8527],
        [ 0.2366],
        [ 0.5618],
        [-0.1146],
        [-0.4615],
        [ 0.0370]])