### Tensors Basics
 - A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

 - Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

In [3]:
import numpy as np

In [6]:
lst = [3,4,5,6]
arr = np.array(lst)

In [7]:
arr

array([3, 4, 5, 6])

In [8]:
arr.dtype

dtype('int32')

## Convert numpy array to PyTorch tensors

In [9]:
tensors = torch.from_numpy(arr)

In [10]:
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [11]:
### Indexing similar to numpy
tensors[:3]

tensor([3, 4, 5], dtype=torch.int32)

In [12]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [13]:
tensors[:-1]

tensor([3, 4, 5], dtype=torch.int32)

In [14]:
tensors[-1]

tensor(6, dtype=torch.int32)

In [15]:
#The tensors and numpy uses same memory locations.
tensors[3] = 100

In [16]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [17]:
arr #we can see that arr also get update value bcoz tensors and numpy uses same memory location.

array([  3,   4,   5, 100])

In [18]:
##Now prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [19]:
tensor_arr[3] = 300

In [20]:
tensor_arr

tensor([  3,   4,   5, 300], dtype=torch.int32)

In [21]:
arr#now we can see that arr does not get updated value.

array([  3,   4,   5, 100])

In [22]:
##zeros and ones
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [23]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [24]:
torch.zeros((3,3), dtype = torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.zeros((3,3), dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [26]:
#two dimensionl array
a = np.arange(0,15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
torch_2d = torch.tensor(a)
torch_2d

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [28]:
torch_2d.ndim

2

In [29]:
torch_2d[:3]

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)

#### Arithmetic Operations

In [30]:
a = torch.tensor([2,3,4], dtype = torch.int64)
b = torch.tensor([5,6,7], dtype = torch.int64)
print(a + b)

tensor([ 7,  9, 11])


In [31]:
print(a - b)

tensor([-3, -3, -3])


In [32]:
print(a * b)

tensor([10, 18, 28])


In [33]:
print(a / b)

tensor([0, 0, 0])


..\aten\src\ATen\native\BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.


In [34]:
#In built function for arithmetic opeartors
torch.add(a,b)

tensor([ 7,  9, 11])

In [35]:
torch.sub(a,b)

tensor([-3, -3, -3])

In [36]:
c = torch.zeros(3)

In [37]:
torch.add(a,b, out = c) #After addition value is stored in the variable 'c'

tensor([ 7.,  9., 11.])

In [40]:
#### Some more operations
torch.add(a,b).sum()

tensor(27)

In [41]:
a.mul(b)

tensor([10, 18, 28])

In [42]:
a.matmul(b) #matrix multiplication

tensor(56)

In [43]:
a.dot(b)

tensor(56)

In [50]:
x = torch.tensor([[2,3,4], [3,4,5]], dtype = torch.int64) ## 2x3 dimension
y = torch.tensor([[4,6],[4, 1],[2,3]], dtype = torch.int64)## 3 x 2 dimension

In [51]:
x.matmul(y)

tensor([[28, 27],
        [38, 37]])

In [52]:
x.mm(y) #short form of matmul

tensor([[28, 27],
        [38, 37]])

In [53]:
x@y #'@' means matrix multiplication

tensor([[28, 27],
        [38, 37]])