#### Modules in PyTorch : Autograd

In [1]:
import torch

In [3]:
#creating tensors
#specifying requires_grad = True, will make sure that gradients will stored for this particular
#tensors whenever we perform some operation on it.
a = torch.ones((2,2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
#now some we perform some operation on tensor.
b = a + 5
print(b)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [5]:
c = b.mean()
c

tensor(6., grad_fn=<MeanBackward0>)

In [6]:
#First we calculate gradient manullay and then verify that using PyTorch
# b = a + 5
# c = mean(b) = sum(a+5) / 4
#now derivative of c wrt a is 1/4 and gradient will be 0.25.

In [7]:
#Now lets verify using PyTorch.
#back propagation
c.backward()

In [8]:
#computing gradient
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


#### Modules in PyTorch : Optim

In [12]:
#The Optim module in PyTorch has prewritten codes for most of the optimizers that are used
#while building neural networks.
#We just have to import them and then they can be used for buliding models.
#importing Optim module
from torch import optim
#adam optimizers
## adam = optim.Adam(model.parameters(), lr = learning_rate)

#SGD optimizers
## sgd = optim.SGD(model.parameters(), lr = learning_rate)

In [13]:
#most of commonly used optimizers are supported in PyTorch.
#Some of them are:
"""SGD
Adam
Adadelta
Adagrad
AdamW
SparseAdam
Adamax
ASGD (Averaged Stochastic Gradient Descent)
RMSprop
Rprop (resilient backpropagation)"""

'SGD\nAdam\nAdadelta\nAdagrad\nAdamW\nSparseAdam\nAdamax\nASGD (Averaged Stochastic Gradient Descent)\nRMSprop\nRprop (resilient backpropagation)'