 - PyTorch Tensors are multidimensional array.

In [1]:
import numpy as np
import torch

In [2]:
a = np.array([2,1,3])
b = np.array([4,3,2])

In [9]:
#Arithmetic operations
print(a + b) # addition
print(a - b) #subtraction
print(a // b) #division
print(a * b) #multiplication

tensor([6, 4, 5], dtype=torch.int32)
tensor([-2, -2,  1], dtype=torch.int32)
tensor([0, 0, 1], dtype=torch.int32)
tensor([8, 3, 6], dtype=torch.int32)


In [4]:
a = torch.from_numpy(a)
b = torch.from_numpy(b)

In [5]:
a

tensor([2, 1, 3], dtype=torch.int32)

In [6]:
b

tensor([4, 3, 2], dtype=torch.int32)

In [8]:
print(a + b) #addition
print(a - b) #subtraction
print(a // b) #division
print(a * b) #multiplication

tensor([6, 4, 5], dtype=torch.int32)
tensor([-2, -2,  1], dtype=torch.int32)
tensor([0, 0, 1], dtype=torch.int32)
tensor([8, 3, 6], dtype=torch.int32)


In [12]:
#Now lets perform matrix operations using PyTorch and Numpy
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(x.shape)

(3, 3)


In [14]:
x = torch.zeros((3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
print(x.size())

torch.Size([3, 3])


In [ ]:
#We have specified the random seed at the begining here so that every time we run the above code,
#the same random number will generate.

In [ ]:
#random.randn() function returns random number that follow a standard normal distribution.

In [26]:
#matrix of random numbers
#setting random seed for numpy
np.random.seed(42)
x = np.random.randn(3,3)
x

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [ ]:
#here tensors filled with random numbers that follow standard distribution.

In [32]:
#now for we setting random seed for pytorch 
torch.manual_seed(42)
x = torch.randn(3,3)
x

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

In [ ]:
#Matrix Operations

In [33]:
#We setting random seed for numpy and create two matrices.
np.random.seed(42)
a = np.random.randn(3,3)
b = np.random.randn(3,3)

In [34]:
#matrix addition
print(np.add(a,b))

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]]


In [36]:
#Matrix subtraction
print(np.subtract(a,b))

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]]


In [39]:
#matrix division
print(np.divide(a,b))

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]]


In [40]:
#Now we setting random seed for tensors and create two tensors.
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)

In [41]:
#matrix addition 
print(torch.add(a,b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [42]:
#matrix subtraction
print(torch.sub(a,b))

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [43]:
#matrix division
print(torch.div(a,b))

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [44]:
#matrix multiplication
print(torch.mul(a,b))

tensor([[ 0.0900,  0.0689,  0.1898],
        [ 0.2557,  1.8974,  0.1843],
        [ 2.1154, -0.8435,  0.3773]])


In [45]:
#Matrix transpose is one technique which is very useful while creating a neural network.

In [46]:
print(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


In [49]:
print(np.transpose(a))

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


In [50]:
#matrix transpose for pytorch
print(torch.t(a))

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


In [51]:
x = np.array(1)
x

array(1)

In [52]:
y = torch.tensor(1)
y

tensor(1)

In [54]:
#lets look at the type of array and type of tensors
type(x), type(y)

(numpy.ndarray, torch.Tensor)

In [55]:
#Concatenating Tensors
#lests create two tensors
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])
print(a, '\n')
print(b)

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])


In [56]:
#now concatenate these two tensors vertically.
#we can see that second tensors has been stacked over first tensors.
torch.cat((a,b))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [57]:
#now concatenate two tensors horizontally by setting parameter dim = 1.
torch.cat((a,b), dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [58]:
# Reshaping Tensors

In [59]:
#setting random seed for pytorch
torch.manual_seed(42)

In [61]:
a = torch.randn(5,3)
a

tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172],
        [-0.7658, -0.7506,  1.3525],
        [ 0.6863, -0.3278,  0.7950]])

In [62]:
a.reshape(3,5)

tensor([[ 0.2674,  0.5349,  0.8094,  1.1103, -1.6898],
        [-0.9890,  0.9580,  1.3221,  0.8172, -0.7658],
        [-0.7506,  1.3525,  0.6863, -0.3278,  0.7950]])

In [63]:
b = torch.randn(2,4)
b

tensor([[ 0.2815,  0.0562,  0.5227, -0.2384],
        [-0.0499,  0.5263, -0.0085,  0.7291]])

In [64]:
b.reshape(4,2)

tensor([[ 0.2815,  0.0562],
        [ 0.5227, -0.2384],
        [-0.0499,  0.5263],
        [-0.0085,  0.7291]])

In [67]:
a.size() #shape of a

torch.Size([5, 3])

In [68]:
b.size() #shape of b

torch.Size([2, 4])

In [69]:
#Converting numpy array to tensors
y = np.array([[3,2], [5,6], [9,1]])
y

array([[3, 2],
       [5, 6],
       [9, 1]])

In [70]:
z = torch.from_numpy(y)
z

tensor([[3, 2],
        [5, 6],
        [9, 1]], dtype=torch.int32)

In [71]:
z.shape

torch.Size([3, 2])