#### Back Propagation Using PyTorch
 - Derivative of  y = x^ 2

In [1]:
import torch

In [3]:
x = torch.tensor(4.0, requires_grad = True)

In [4]:
x

tensor(4., requires_grad=True)

In [5]:
y = x**2
y #return square of 4

tensor(16., grad_fn=<PowBackward0>)

In [6]:
### Back propagation y = 2* x
y.backward()

In [7]:
print(x.grad)

tensor(8.)


In [16]:
x = torch.tensor(2.0, requires_grad = True)
x

tensor(2., requires_grad=True)

In [17]:
y = x ** 3
y

tensor(8., grad_fn=<PowBackward0>)

In [18]:
#back propagation  y = 3*x ** 2
y.backward()

In [19]:
print(x.grad)

tensor(12.)


In [20]:
lst = [[2.,3.,4.], [4.,5.,6.], [1.,4.,2.]]
torch_input = torch.tensor(lst, requires_grad = True)

In [21]:
torch_input

tensor([[2., 3., 4.],
        [4., 5., 6.],
        [1., 4., 2.]], requires_grad=True)

In [22]:
torch_input.ndim

2

In [23]:
torch_input.shape

torch.Size([3, 3])

In [24]:
## y= x**3 + x**2 in forward propagation
##derivatin of y = 3* x**2 + 2 *x in backpropagation
y = torch_input **3 + torch_input ** 2
y

tensor([[ 12.,  36.,  80.],
        [ 80., 150., 252.],
        [  2.,  80.,  12.]], grad_fn=<AddBackward0>)

In [25]:
z = y.sum()
z

tensor(704., grad_fn=<SumBackward0>)

In [26]:
z.backward()

In [27]:
### y = 3* x **2 + 2 * x #here x in torch_input
torch_input.grad

tensor([[ 16.,  33.,  56.],
        [ 56.,  85., 120.],
        [  5.,  56.,  16.]])

In [51]:
m = torch.tensor([3.5,2])
m

tensor([3.5000, 2.0000])

In [54]:
k =k.new_ones(3,3, dtype = torch.double)
k

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [55]:
k = torch.rand_like(k, dtype = torch.float)
k

tensor([[0.0117, 0.9015, 0.1021],
        [0.8407, 0.1651, 0.6820],
        [0.4504, 0.1048, 0.9803]])

In [56]:
k.size()

torch.Size([3, 3])

In [61]:
#the reshape tensor using torch.view() method
k.view(3,3)

tensor([[0.0117, 0.9015, 0.1021],
        [0.8407, 0.1651, 0.6820],
        [0.4504, 0.1048, 0.9803]])

In [63]:
x = torch.rand(4,4,dtype = torch.float)
y = x.view(16)
z = x.view(-1,8) #the size -1 is inferred from other dimensions

In [64]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [65]:
z

tensor([[0.6563, 0.3528, 0.2435, 0.8899, 0.9963, 0.4830, 0.2815, 0.8871],
        [0.0357, 0.3736, 0.4989, 0.9885, 0.9215, 0.4947, 0.0807, 0.1180]])

In [66]:
y

tensor([0.6563, 0.3528, 0.2435, 0.8899, 0.9963, 0.4830, 0.2815, 0.8871, 0.0357,
        0.3736, 0.4989, 0.9885, 0.9215, 0.4947, 0.0807, 0.1180])

In [67]:
x

tensor([[0.6563, 0.3528, 0.2435, 0.8899],
        [0.9963, 0.4830, 0.2815, 0.8871],
        [0.0357, 0.3736, 0.4989, 0.9885],
        [0.9215, 0.4947, 0.0807, 0.1180]])

In [70]:
#if we have one element tensor, we use .item() to get value as a python number
p = torch.randn(1)
p

tensor([-0.2285])

In [71]:
print(p.item())

-0.228496253490448


In [72]:
torch.cuda.is_available()

False

In [73]:
#converting torch tensors to a numpy array
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [74]:
b = a.numpy()
b

array([1., 1., 1.], dtype=float32)

In [75]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2.])
[2. 2. 2.]


In [77]:
#Now converting numpy array to torch tensors
import numpy as np
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [78]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [79]:
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
