### TENSORS
 - Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.
 - Tensors and Numpy arrays can share the same memory locations.

In [1]:
import torch
import numpy as np

In [2]:
##Tensors can be created directly from the data.
data = [[1,2], [3,4]]
data

[[1, 2], [3, 4]]

In [3]:
type(data)

list

In [4]:
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
type(x_data)

torch.Tensor

In [6]:
#Torch can be created from Numpy Array.
arr = np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [7]:
arr_tensor = torch.tensor(arr)
arr_tensor

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [8]:
type(arr_tensor)

torch.Tensor

In [10]:
arr_tensor.dtype

torch.int32

In [13]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor : \n {x_ones}")

x_rand = torch.rand_like(x_data, dtype = torch.float) #override the data type of x_data
print(f"Random Tensor : \n{x_rand}")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]])
Random Tensor : 
tensor([[0.2730, 0.0466],
        [0.1219, 0.0790]])


#### Attributes of a Tensor
 - Tensor attributes describe their shape, datatype and the device on which they are stored.

In [14]:
tensors = torch.rand(3,4)

print(f"Shape of tensors : {tensors.shape}")
print(f"Datatype of tensors : {tensors.dtype}")
print(f"Device tensor is stored on : {tensors.device}")

Shape of tensors : torch.Size([3, 4])
Datatype of tensors : torch.float32
Device tensor is stored on : cpu


### Operations on Tensors

In [16]:
#Standard numpy-like indexing and slicing

x = torch.ones(4, 4)
print("First row: ", x[0])
print("First Column : ", x[:, 0])
print("Last Column : ", x[:, -1])

x[:, 1] = 0 #adding zero value at first column
print(x)

First row:  tensor([1., 1., 1., 1.])
First Column :  tensor([1., 1., 1., 1.])
Last Column :  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
#Joining Tensors
tensor_concat = torch.cat([x,x], dim = 1) #joning tensors along column-wise
tensor_concat

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])

In [20]:
tensor_stack = torch.stack([x, x], dim = 1) #stacking tensors along columns - wise
tensor_stack

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.]]])

In [21]:
type(tensor_stack)

torch.Tensor

### Arithmetic Operations


In [24]:
x

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [22]:
#Matrix Multiplication

y1 = x @ x.T
y2 = x.matmul(x.T)
y3 = torch.rand_like(x)

print(y1)
print(y2)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[0.6878, 0.3932, 0.7721, 0.0931],
        [0.0669, 0.3466, 0.8814, 0.3738],
        [0.0309, 0.8869, 0.8325, 0.6822],
        [0.1756, 0.5878, 0.5942, 0.6581]])


In [23]:
torch.matmul(x, x.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
##Element-wise product
z1 = x * x
z2 = x.mul(x)
z3 = torch.rand_like(x)
print(z1)
print(z2)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[0.2165, 0.2614, 0.8500, 0.7580],
        [0.4175, 0.1494, 0.2606, 0.0187],
        [0.3439, 0.2371, 0.6227, 0.5400],
        [0.9365, 0.8733, 0.1480, 0.5819]])


In [26]:
torch.mul(x, x, out= z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
agg = x.sum()
agg

tensor(12.)

In [30]:
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [31]:
#In-place operations = Operations that store result into the operand are called in-place.
#They are denoted by a '_' suffix.
#For example : x.copy_(), x.t_() will change x.

In [33]:
print(x, '\n')
x.add_(5)
print(x)

tensor([[2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.]]) 

tensor([[7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.]])


In [34]:
x.copy_(x)

tensor([[7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.]])

In [37]:
x.t_()

tensor([[7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.],
        [7., 5., 7., 7.]])

In [38]:
x.tril_()

tensor([[7., 0., 0., 0.],
        [7., 5., 0., 0.],
        [7., 5., 7., 0.],
        [7., 5., 7., 7.]])